Feature/register
andreihojda15/cryptoexchange pull request #2
Opened 2022-04-26 19:46 UTC by andreihojda15

2022-04-29 14:34 UTC, denisslon-csv commented on routes/register.js
> +    // check if there already exists a user with the same email, username and phonenumber
Instead of performing 3 different "findOne's" on Users, you could perform just one and group your conditions using $or operand, which will return the first entry whether one of the conditions is satisfied. And after that, if there is 1 user found, just check which of the field is equal to your parameters in order to return custom error message.
Something like:

```suggestion
    // check if there already exists a user with the same email, username and phonenumber
    const findUser = await Users.findOne({  
        $or: [
             { username: username },
             { phonenumber: phonenumber },
             { email: email }
        ]
    });
    
    if (findUser.username === username) {
         return res.json({
             msg: "This username has already been used"
         });
     }
     
     if (findUser.email === email) {
         return res.json({
             msg: "This email address has already been used"
         });
     }
     
     if (findUser.phonenumber === phonenumber) {
         return res.json({
             msg: "This phone number has already been used"
         });
     }
```

2022-04-29 14:36 UTC, denisslon-csv requested changes
A bit of refactoring, please see the suggestions provided

2022-04-29 14:47 UTC, denisslon-csv commented on index.js
> +var registerRoutes = require('./routes/register.js');
You should use const instead of var here

2022-04-29 14:54 UTC, denisslon-csv commented on routes/register.js
> +    }
I would suggest moving this validation before any db query is performed

2022-04-29 17:36 UTC, andreihojda15 commented on routes/register.js
> +    // check if there already exists a user with the same email, username and phonenumber
I am getting an error here. If there's no user in the db that satisfies one of the 3 conditions then findUser will be null and I am getting an error at the first if (the one that checks username)
I wish to ask if this suggestion is alright (it works for me when running the app and testing with postman)
```suggestion
    // check if there already exists a user with the same email, username and phonenumber
    const findUser = await Users.findOne({  
        $or: [
             { username: username },
             { phonenumber: phonenumber },
             { email: email }
        ]
    });
    
    if(findUser){
        if(findUser.username === username) {
            return res.json({
                msg: "This username has already been used"
            });
        }
        
        if(findUser.email === email) {
            return res.json({
                msg: "This email address has already been used"
            });
        }
    
        if(findUser.phonenumber === phonenumber) {
            return res.json({
                msg: "This phone number has already been used"
            });
        }
    }
```

2022-04-29 17:38 UTC, andreihojda15 commented on index.js
> +var registerRoutes = require('./routes/register.js');
Changed, I will push remotely with the other suggestions

2022-04-29 17:39 UTC, andreihojda15 commented on routes/register.js
> +var bcrypt = require('bcrypt');
Changed

2022-04-29 17:40 UTC, andreihojda15 commented on routes/register.js
> +    }
Done

2022-04-29 17:40 UTC, andreihojda15 commented on routes/register.js
> +        password: hashPass
Understood!

2022-04-30 06:37 UTC, denisslon-csv commented on routes/register.js
> +    // check if there already exists a user with the same email, username and phonenumber
It was just a suggestion, not a complete solution :)
But for the case when findUser is null you can either wrap all 3 if statements in another if checking if there is an user found or you can just use optional chaining for the findUser, like:

`if ( findUser?.username === username )` 

If findUser is null the optional chaining '?.' will give you an 'undefined' value and will not throw an error, now you will be comparing undefined === username

2022-05-01 10:29 UTC, andreihojda15 commented on routes/register.js
> +    // check if there already exists a user with the same email, username and phonenumber
thank you! I implemented and pushed the suggestions (also applied the optional chaining for the 3 if statements used for custom error message)

2022-05-02 05:31 UTC, denisslon-csv approved these changes

2022-08-28 16:36 UTC, closed without merging